### ISSUE TITLE
Do we need the overloaded C++ functions?

### ISSUE THREAD

**Issue by bvisness** [HandmadeMath/HandmadeMath#108]
I'm not sure we gain anything by having the overloaded versions of things like `HMM_Multiply` or `HMM_Add`. They are not really less verbose than the full names, we provide operator overloads for all the important ones, and they are a lot of work to maintain.

Obviously we can keep them if they are useful to people, but I figured I'd ask the question. I personally have stopped using overloaded functions completely in my own code and haven't minded. (Thanks, Go.)

**Comment by StrangeZak** [comment]
I could imagine some C++ like this feature of just being able to call HMM_Multiply with whatever data types and not have to call the explicit functions for that data type. Either way I’m not torn on keeping them or not

**Comment by RandyGaul** [comment]
Personally I prefer mul kind of function in C++.

The reason is if we concatenate a few matrices like so:

```cpp
D = A * B * C
D = C * B * A
```

It isn't extremely clear what the order of intended operations is just by looking at the `*` operator. But, if there is a mul function people can use either ordering however they like, explicitly.

```cpp
D = mul(mul(A, B), C);
D = mul(mul(B, C), A);
```

I overload this mul function for matrix to matrix, matrix to vector, quaternion to vector, axis-angle to vector, and so-on, transform to transform, transform to vector, and so on.

**Comment by Nairou** [comment]
I no longer use the overloaded functions either. I have also been tripped up in the past by reading two versions of each operation in the documentation (usually via search), trying one, and learning it was just an overload of something else.

**Comment by bvisness** [comment]
@Nairou That's an interesting case I hadn't thought of. And to @RandyGaul's point, if you want to use the `mul` style of math, the function names are probably so verbose that you would have to `#define mul HMM_Multiply` anyway, just to make them tolerable. 

My biggest issue with the overloaded versions is that they don't really give you anything beyond the operator overloads (besides a more visible order of operations, I guess). If someone wants to take the @RandyGaul approach, I would rather just let them create `mul` in their own project with all the overloads they want. That way they can extend it to other things outside of Handmade Math.

**Comment by bvisness** [comment]
HMM 2.0 preserves the C++ overloads.
