### ISSUE TITLE
CI is not working

### ISSUE THREAD

**Issue by bvisness** [HandmadeMath/HandmadeMath#134]
For some reason our Travis CI builds have stopped working. I tried uninstalling the app and re-linking it, to no avail. Travis doesn't even show me the Handmade Math organization, despite GitHub thinking there is an active link there.

Either we need to figure out how to get Travis working again, or we need to migrate to a different CI system.

**Comment by StrangeZak** [comment]
We could try moving over to Github Actions?

**Comment by bvisness** [comment]
I fixed this for HMM 2.0.
