### ISSUE TITLE
Request - document fundamental choices made in handmade math

### ISSUE THREAD

**Issue by mlabbe** [HandmadeMath/HandmadeMath#144]
HMM is very useful when bringing up a new 3D scene.  Eventually, however, a user may run into a scenario where they are troubleshooting their coordinate system, need to view a matrix in a debugger, or understand where a point lies in clip space.  It would be helpful for these troubleshooters if HMM documented the following:

 - Whether HMM's functions assume RHS or LHS coordinate systems
 - If the generated matrices are column-major or row-major
 - If the perspective projection matrix function targets a clip space of [-1, +1], [0, 1] or something else.

Of course, all of these things can be discovered  by investigating the results of function calls, but removing them from question would help users reach their intended application state sooner.

Thanks!

EDIT: Related, but not equivalent: #75

**Comment by StrangeZak** [comment]
This is something i can do soon. Thanks for the suggestion :)

**Comment by bvisness** [comment]
I added a little extra to the README.
