### ISSUE TITLE
Use _Generic in C?

### ISSUE THREAD

**Issue by bvisness** [HandmadeMath/HandmadeMath#148]
@floooh suggested to me that we could use `_Generic` to give C users some of the C++ experience, such as `HMM_Mul` instead of `HMM_MulV2F`, `HMM_MulV3F`, etc. I [gave it a spin in godbolt](https://godbolt.org/z/eq5fnjj5P) and damn it feels nice.

I'd like to do this, although @StrangeZak expressed some concern to me about it being very new to MSVC? Given that it's part of the C11 standard, though, I think it would be nice to include, as long as we can nicely ifdef it out for those using older MSVC. Are there other considerations we should make there?

**Comment by StrangeZak** [comment]
I’m good with adding them as long as we can properly exclude them on non-C11 compilers (Basically older MSVC version), and C++

**Comment by floooh** [comment]
If the check for _Generic support turns out to be tricky across the various compilers, the _Generic stuff could excluded by default and enabled with a user-provided config flag similar to ```HANDMADE_MATH_NO_SSE```.

**Comment by bvisness** [comment]
Done in HMM 2.0
