### ISSUE TITLE
Unroll our loops

### ISSUE THREAD

**Issue by bvisness** [HandmadeMath/HandmadeMath#150]
Wherever we use a loop for a vector or matrix operation, we should manually unroll it to be friendlier to compilers and (generally) get better debug performance.

Discord discussion: https://discord.com/channels/239737791225790464/1065836155779694744

Blocked by #149

**Comment by StrangeZak** [comment]
Good idea, lets do this 👍

**Comment by bvisness** [comment]
Done in #153
