### ISSUE TITLE
Convert HandmadeMath to double

### ISSUE THREAD

**Issue by k-novak** [HandmadeMath/HandmadeMath#157]
Hi,

I would like to use this library with my simulation code, but I need high accuracy.
I am wondering, how complicated to convert the library from float to double?
I am not familiar with SSE, so unfortunately I cannot judge it.
It would be great to set the accuracy with t #define. Any plan to implement double accuracy, or add it to the roadmap?

K

**Comment by bvisness** [comment]
Handmade Math is designed for games and other low-precision applications. It makes no special provisions for numerical accuracy, only for numerical _consistency_ across platforms. 

That said, you can just switch floats to doubles in the vector and matrix types and fix whatever compiler errors arise. We won't be modifying the library to add double support.
