### ISSUE TITLE
Audit use of pass-by-reference in C++ functions / operator overloads

### ISSUE THREAD

**Issue by xparq** [HandmadeMath/HandmadeMath#163]
Hey there, lovely stuff, I just noticed these weird vector operator arg defs that look like copy-pasted remnants of an idea that may not actually be justified, I guess.

**Comment by bvisness** [comment]
I don't know what you mean. They allow you to access elements of vectors by index without writing `.Elements`, if you're using C++. So like `myVec3[2]` instead of `myVec3.Elements[2]`.

**Comment by xparq** [comment]
Ahh, sorry, I though the issue title was self-explanatory, but there's always room for misunderstanding. :)

I meant the operator's signature, of course, and (as I noted), specifically its arg. passing approach.

IOW, why the ref? Just pass `Index` by-val.

**Comment by bvisness** [comment]
> I meant the operator's signature, of course

When working with humans, I recommend communicating using words and sentences so humans can understand.

Pass-by-reference vs. pass-by-val literally doesn't matter: https://godbolt.org/z/jT63zqWWh. If you believe it _does_ matter and can demonstrate this in godbolt, perhaps we can consider making a change.

**Comment by xparq** [comment]
_Wow, sorry that my friendly suggestion, _and_ my apology both apparently rubbed you the wrong way.
In the hope of some understanding, still: given the context of a) maths, b) C++ coding, and c) the pretty common & well-known old C++ habit of passing everything* by const&, I thought that my -- admittedly too condensed -- message would click. **I totally understand that it didn't, absolutely fine, maybe even I wouldn't understand it myself. I should've been less cryptic. Sorry, again.** And misunderstandings are indeed abundant, everywhere, all the time, with everybody -- most of the time we just don't even notice. That's what I meant by my sarcastic remark, and nothing personal._

\* _(except for doubles, where it might actually matter (e.g. in 32-bit code) -- that slight inconsistency was what actually made me assume (wrongly then, I suppose) that it could probably be a copy-paste remnant from older versions, or something)_

----
As to Godbolt and stuff: I didn't mean to suggest it for performance, I meant it for a slight code readability improvement (noise reduction), precisely because the more convoluted formulation has no benefits.

**Comment by RandyGaul** [comment]
Passing everything by pointers or references is not a good habit for certain code as it can introduce pointer aliasing and cause a performance hit.

**Comment by bvisness** [comment]
Sure, so if we want to assess values vs. references then we should do so holistically and not for some specific operators based on "readability".

Currently we have:

- `float &operator[](const int &Index)` (get vector element)
- `HMM_VecN &operator[](const int &Index)` (get matrix column)
- `HMM_T operator+(HMM_T Left, HMM_T Right)` (add, subtract, multiply, and divide vectors, matrices, and quaternions)
- `HMM_VecN &operator+=(HMM_VecN &Left, HMM_VecN Right)` (same operators combined with assignment)
- `HMM_VecN operator*(HMM_VecN Left, float Right)` (vector or matrix * float, and the reverse)
- `HMM_VecN operator*(HMM_MatN Matrix, HMM_VecN Vector)` (matrix * vector)
- `HMM_Bool operator==(HMM_VecN Left, HMM_VecN Right)` (vector equality and inequality)
- `HMM_VecN operator-(HMM_VecN In)` (vector negation)

Clearly most of them are indeed passing by value. I suppose we have to trade off the costs of copies vs. the cost of pointer aliasing, but surely these will almost always be inlined anyway. If passing by reference makes it _less_ likely to inline due to pointer aliasing, then yeah, we should probably switch.

**Comment by RandyGaul** [comment]
I took a quick look at this function:

```cpp
static inline HMM_Vec4 &operator*=(HMM_Vec4 &Left, float Right)
{
    ASSERT_COVERED(HMM_MulV4FAssign);
    return Left = Left * Right;
}
```

And compiled this program with MSVC 2019 using default Debug/Release settings (/Od and /O2 respectively).

```cpp
#include <stdio.h>

#include "HandmadeMath.h"

int main()
{
	HMM_Vec4 v = HMM_V4(1.0f, 2.0f, 3.0f, 4.0f);
	v *= 2;

	printf("%f, %f, %f, %f\n", v.X, v.Y, v.Z, v.W);

	return 0;
}
```

For debug mode there isn't a significant difference between using references or not. However, when compiling in Release with /O2 we can see a difference.

With references:

```cpp
int main()
{
00007FF738AB1070  sub         rsp,38h  
	HMM_Vec4 v = HMM_V4(1.0f, 2.0f, 3.0f, 4.0f);
	v *= 2;
00007FF738AB1074  movaps      xmm5,xmmword ptr [__xmm@4100000040c000004080000040000000 (07FF738AB2250h)]  

	printf("%f, %f, %f, %f\n", v.X, v.Y, v.Z, v.W);
00007FF738AB107B  lea         rcx,[string "%f, %f, %f, %f\n" (07FF738AB2240h)]  
00007FF738AB1082  movaps      xmm0,xmm5  
00007FF738AB1085  xorps       xmm4,xmm4  
00007FF738AB1088  shufps      xmm0,xmm5,0FFh  
00007FF738AB108C  movaps      xmm1,xmm5  
00007FF738AB108F  cvtss2sd    xmm4,xmm0  
00007FF738AB1093  shufps      xmm1,xmm5,0AAh  
00007FF738AB1097  xorps       xmm3,xmm3  
00007FF738AB109A  cvtss2sd    xmm3,xmm1  
00007FF738AB109E  movaps      xmm0,xmm5  
00007FF738AB10A1  movsd       mmword ptr [rsp+20h],xmm4  
00007FF738AB10A7  shufps      xmm0,xmm5,55h  
00007FF738AB10AB  xorps       xmm2,xmm2  
00007FF738AB10AE  xorps       xmm1,xmm1  
00007FF738AB10B1  movq        r9,xmm3  
00007FF738AB10B6  cvtss2sd    xmm2,xmm0  
00007FF738AB10BA  cvtss2sd    xmm1,xmm5  
00007FF738AB10BE  movq        r8,xmm2  
00007FF738AB10C3  movq        rdx,xmm1  
00007FF738AB10C8  call        printf (07FF738AB1010h) 
```

| Instruction | # of appearances |
| --- | --- |
| sub| 1 |
| movaps | 4 |
| xorps | 4 |
| shufps | 3 |
| movq | 3 |
| movsd | 1 |
| lea | 1 |

Without references:

```cpp
int main()
{
00007FF717321070  sub         rsp,38h  
	HMM_Vec4 v = HMM_V4(1.0f, 2.0f, 3.0f, 4.0f);
	v *= 2;

	printf("%f, %f, %f, %f\n", v.X, v.Y, v.Z, v.W);
00007FF717321074  movsd       xmm3,mmword ptr [__real@4008000000000000 (07FF717322260h)]  
00007FF71732107C  lea         rcx,[string "%f, %f, %f, %f\n" (07FF717322240h)]  
00007FF717321083  movsd       xmm2,mmword ptr [__real@4000000000000000 (07FF717322258h)]  
00007FF71732108B  movq        r9,xmm3  
00007FF717321090  movsd       xmm1,mmword ptr [__real@3ff0000000000000 (07FF717322250h)]  
00007FF717321098  movq        r8,xmm2  
00007FF71732109D  movsd       xmm0,mmword ptr [__real@4010000000000000 (07FF717322268h)]  
00007FF7173210A5  movq        rdx,xmm1  
00007FF7173210AA  movsd       mmword ptr [rsp+20h],xmm0 
00007FF6D4FC10B0  call        printf (07FF6D4FC1010h) 
```

| Instruction | # of appearances |
| --- | --- |
| sub| 1 |
| movsd | 5 |
| lea | 1 |
| movq | 3 |

Now I'm definitely not all that experienced at reading assembly, but the latter certainly looks preferable to me. I'd say go ahead and pass things around by value for all your operators.
