### ISSUE TITLE
NEON Support 

### ISSUE THREAD

**Issue by StrangeZak** [HandmadeMath/HandmadeMath#79]
Just wanted to get some opinions on if its worth it or not to optimize Handmade Math for NEON (Arm CPU SIMD instructions). Its something i've been thinking about doing recently although i am not comfortable with the instructions so it would require quiet a bit of work.

I am willing to do it though, im just looking to see if there's interest / anyone using handmade math on a ARM based CPU.

**Comment by kaervin** [comment]
I would be interested in NEON support.
Would be great for any game/project that comes to the switch, a platform I have thought about releasing on.

**Comment by StrangeZak** [comment]
My current project im working on is also targeting The Switch, on the games repo there's a Handmade Math Version with support the NEON SIMD instruction set. Ill look at pulling it out and moving it into public handmade math version but it might take a bit of time

**Comment by kaervin** [comment]
That would be nice!

**Comment by StrangeZak** [comment]
@bvisness Just so you are aware, I have recently gotten one of the new M1 Macbooks and more or less have an ARM implementation mostly complete. It's been tested on both an RPI 4 and an M1 Macbook Pro. I need to clean it up a bit still, but there will a very large PR for this coming in soon.

**Comment by bvisness** [comment]
Depending on how big our various backends get, I'm starting to wonder if we should build and ship three separate versions of the library - no SIMD, SSE, NEON. Maybe something to consider for version 2.0?

**Comment by bvisness** [comment]
Closed by #169!
